# Project information
site_name: "GMEM: Generalized Memory Management"
site_url: https://gmem.tech
site_author: dev@openeuler.org

# Repository
repo_name: openEuler/GMEM
repo_url: https://github.com/GMEM-Team/gmem-team.github.io
edit_uri: https://github.com/GMEM-Team/gmem-team.github.io/tree/master/docs

# Copyright
copyright: Copyright &copy; 2023 openEuler GMEM team

# Pages
nav:
- Home: en/index.md

theme:
  name: material
  language: en

extra:
  alternate:
    - name: Chinese
      link: /zh/
      lang: zh
    - name: English
      link: /en/
      lang: en
